# Generated by Django 5.1.7 on 2025-09-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_auth',
            name='Conf_pass',
        ),
        migrations.AddField(
            model_name='user_auth',
            name='Active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_auth',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
