# Generated by Django 5.1.7 on 2025-09-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_user_auth_conf_pass_user_auth_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_auth',
        ),
    ]
