# Generated by Django 5.1.7 on 2025-09-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=80, null=True)),
                ('Gender', models.CharField(max_length=20, null=True)),
                ('Address', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
