# Generated by Django 5.1.7 on 2025-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_create_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
