# Generated by Django 5.1.7 on 2025-09-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.TextField(max_length=20)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
